name: axon
services:
  postgresql:
    image: index.docker.io/postgres:17.2@sha256:3267c505060a0052e5aa6e5175a7b41ab6b04da2f8c4540fc6e98a37210aa2d3
    init: true
    restart: unless-stopped
    container_name: $POSTGRES_HOST
    hostname: $POSTGRES_HOST
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - axon-network
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  keycloak:
    image: quay.io/keycloak/keycloak:26.1@sha256:75ca4b2e4e954ff89c20ba8e5aeeef3bd0d250847fedb1c9752949823b319dda
    init: true
    restart: unless-stopped
    container_name: $KEYCLOAK_HOST
    hostname: $KEYCLOAK_HOST
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: $KEYCLOAK_HTTP_PORT
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL_HOST: $POSTGRES_HOST
      KC_DB_URL_PORT: $POSTGRES_PORT
      KC_DB_URL_DATABASE: $POSTGRES_DB
      KC_DB_SCHEMA: $KEYCLOAK_SCHEMA
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - axon-network
    ports:
      - $KEYCLOAK_HTTP_PORT:$KEYCLOAK_HTTP_PORT
      - $KEYCLOAK_HTTPS_PORT:$KEYCLOAK_HTTPS_PORT
    command: [ "start-dev", "--http-port", "$KEYCLOAK_HTTP_PORT", "--https-port", "$KEYCLOAK_HTTPS_PORT" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:$KEYCLOAK_HTTP_PORT/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    depends_on:
      postgresql:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
  migrator:
    build:
      context: ../..
      dockerfile: ./images/migrator.Dockerfile
    init: true
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      MIGRATIONS_PATH: $MIGRATIONS_PATH
    volumes:
      - ../../sql:$MIGRATIONS_PATH:ro
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - axon-network
  server:
    build:
      context: ../..
      dockerfile: ./images/server.Dockerfile
    init: true
    restart: unless-stopped
    container_name: server
    hostname: server
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SERVER_PORT: $SERVER_PORT
      SERVER_CERT_PATH: $SERVER_CERT_PATH
      SERVER_KEY_PATH: $SERVER_KEY_PATH
      SERVER_JWKS_URLS: $SERVER_JWKS_URLS
      SERVER_POLICY_PATH: $SERVER_POLICY_PATH
    volumes:
      - type: bind
        read_only: true
        source: ./server.crt.pem
        target: /etc/axon/server/server.crt.pem
      - type: bind
        read_only: true
        source: ./server.key.pem
        target: /etc/axon/server/server.key.pem
      - type: bind
        read_only: true
        source: ./policy.rego
        target: /etc/axon/server/policy.rego
    depends_on:
      migrator:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - axon-network
networks:
  axon-network:
    driver: bridge
    name: axon-network
