name: axon
services:
  postgresql:
    image: index.docker.io/postgres:17.2@sha256:3267c505060a0052e5aa6e5175a7b41ab6b04da2f8c4540fc6e98a37210aa2d3
    init: true
    restart: unless-stopped
    container_name: $POSTGRES_HOST
    hostname: $POSTGRES_HOST
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - axon-network
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  keycloak:
    image: quay.io/keycloak/keycloak:26.1@sha256:75ca4b2e4e954ff89c20ba8e5aeeef3bd0d250847fedb1c9752949823b319dda
    init: true
    restart: unless-stopped
    container_name: $KEYCLOAK_HOST
    hostname: $KEYCLOAK_HOST
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: $KEYCLOAK_HTTP_PORT
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL_HOST: $POSTGRES_HOST
      KC_DB_URL_PORT: $POSTGRES_PORT
      KC_DB_URL_DATABASE: $POSTGRES_DB
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - axon-network
    ports:
      - $KEYCLOAK_HTTP_PORT:$KEYCLOAK_HTTP_PORT
      - $KEYCLOAK_HTTPS_PORT:$KEYCLOAK_HTTPS_PORT
    command: [ "start-dev", "--http-port", "$KEYCLOAK_HTTP_PORT", "--https-port", "$KEYCLOAK_HTTPS_PORT" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:$KEYCLOAK_HTTP_PORT/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
networks:
  axon-network:
    driver: bridge
    name: axon-network
